# Generated by Django 3.1.7 on 2021-03-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.BooleanField()),
                ('receiver_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='bank.accounts')),
                ('sender_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='bank.accounts')),
            ],
        ),
    ]
