# Generated by Django 3.1.7 on 2021-03-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
