# Generated by Django 3.1.7 on 2021-03-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20210307_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='Amount',
            new_name='Balance',
        ),
    ]
